/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_avmodule_AvSoftDecoder */

#ifndef _Included_io_agora_avmodule_AvSoftDecoder
#define _Included_io_agora_avmodule_AvSoftDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_distillMediaInfo
 * Signature: (Ljava/lang/String;Lio/agora/avmodule/AvMediaInfo;)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1distillMediaInfo
        (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_parserOpen
 * Signature: (Lio/agora/avmodule/AvDecParam;)J
 */
JNIEXPORT jlong JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1parserOpen
        (JNIEnv *, jobject, jobject);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_parserClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1parserClose
        (JNIEnv *, jobject, jlong);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_getInMediaInfo
 * Signature: (JLio/agora/avmodule/AvMediaInfo;)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1getInMediaInfo
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_parserInputPacket
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1parserInputPacket
        (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_parserDecVideoFrame
 * Signature: (JLio/agora/avmodule/AvVideoFrame;)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1parserDecVideoFrame
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_parserGetVideoFrame
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1parserGetVideoFrame
        (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_parserDecAudioFrame
 * Signature: (JLio/agora/avmodule/AvAudioFrame;)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1parserDecAudioFrame
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_parserGetAudioFrame
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1parserGetAudioFrame
        (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_yuvToBitmap
 * Signature: ([BIIIILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1yuvToBitmap
        (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jobject);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_bitmapToYuv
 * Signature: (Ljava/lang/Object;I[B)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1bitmapToYuv
        (JNIEnv *, jobject, jobject, jint, jbyteArray);

/*
 * Class:     io_agora_avmodule_AvSoftDecoder
 * Method:    native_bmpSaveToFile
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvSoftDecoder_native_1bmpSaveToFile
        (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
